### ISSUE TITLE
Enhancement: Better diagnostics for errors.

### ISSUE THREAD

**Issue by kolban-google** [GoogleCloudPlatform/cloud-data-quality#156]
While studying CloudDQ, I created a configuration file and used it in an execution.   I obviously made a mistake in my config file which has resulted in the error: `ERROR malformed JSON`.   The issue I am reporting here is in terms of "servicability".  Based on the information presented in this error output, how can I narrow down on my issue?  Is there an opportunity for the project to offer "better" diagnostics?
```
python3 clouddq_executable_v0.5.2_debian_10_python3.9.zip \
    ALL \
    test1.yaml \
    --gcp_project_id="${GOOGLE_CLOUD_PROJECT}" \
    --gcp_bq_dataset_id="${CLOUDDQ_BIGQUERY_DATASET}" \
    --gcp_region_id="${CLOUDDQ_BIGQUERY_REGION}" \
    --print_sql_queries \
    --target_bigquery_summary_table="${CLOUDDQ_TARGET_BIGQUERY_TABLE}"kolban@cloudshell:~/clouddq (kolban-dataplex)$ ./run
Your active configuration is: [cloudshell-11175]
2022-03-05 16:12:46 cs-158005325041-default clouddq.integration.gcp_credentials[1748] INFO Successfully created GCP Client.
2022-03-05 16:12:46 cs-158005325041-default clouddq[1748] INFO Starting CloudDQ run with configs:
{"clouddq_run_configs": {"rule_binding_ids": "ALL", "rule_binding_config_path": "test1.yaml", "dbt_path": null, "dbt_profiles_dir": null, "environment_target": "dev", "gcp_project_id": "kolban-dataplex", "gcp_region_id": "us-central1", "gcp_bq_dataset_id": "dq_output", "gcp_service_account_key_path": null, "gcp_impersonation_credentials": null, "metadata": "{}", "dry_run": false, "progress_watermark": true, "target_bigquery_summary_table": "kolban-dataplex.dq_output.target", "debug": false, "print_sql_queries": true, "skip_sql_validation": false, "summary_to_stdout": false, "enable_experimental_bigquery_entity_uris": false, "enable_experimental_dataplex_gcs_validation": false, "bigquery_client": null, "gcp_credentials": {"credentials": "<google.auth.compute_engine.credentials.Credentials object at 0x7fa1709d60a0>", "project_id": "kolban-dataplex", "user_id": "kolban@kolban.altostrat.com"}}}
2022-03-05 16:12:46 cs-158005325041-default clouddq.runners.dbt.dbt_connection_configs[1748] INFO Using Application-Default Credentials (ADC) to authenticate to GCP...
2022-03-05 16:12:46 cs-158005325041-default clouddq[1748] INFO Writing rule_binding views and intermediate summary results to BigQuery dq_summary_table_name: `kolban-dataplex.dq_output.dq_summary`. 
2022-03-05 16:12:46 cs-158005325041-default clouddq[1748] INFO Using dq_summary_dataset: kolban-dataplex.dq_output
2022-03-05 16:12:46 cs-158005325041-default clouddq[1748] INFO Using target_bigquery_summary_table: `kolban-dataplex.dq_output.target`. 
2022-03-05 16:12:47 cs-158005325041-default clouddq[1748] INFO Preparing SQL for rule bindings: ['SALES_WIDGET', 'SALES_QUANTITY']
2022-03-05 16:12:47 cs-158005325041-default clouddq[1748] ERROR malformed JSON
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/clouddq/clouddq/main.py", line 486, in main
    configs_cache.get_entities_configs_from_rule_bindings(
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/clouddq/clouddq/classes/dq_configs_cache.py", line 354, in get_entities_configs_from_rule_bindings
    for record in self._cache_db.query(query):
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/py_deps/pypi__sqlite_utils/sqlite_utils/db.py", line 410, in query
    cursor = self.execute(sql, params or tuple())
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/py_deps/pypi__sqlite_utils/sqlite_utils/db.py", line 422, in execute
    return self.conn.execute(sql, parameters)
sqlite3.OperationalError: malformed JSON
"malformed JSON"
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/clouddq/clouddq/main.py", line 486, in main
    configs_cache.get_entities_configs_from_rule_bindings(
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/clouddq/clouddq/classes/dq_configs_cache.py", line 354, in get_entities_configs_from_rule_bindings
    for record in self._cache_db.query(query):
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/py_deps/pypi__sqlite_utils/sqlite_utils/db.py", line 410, in query
    cursor = self.execute(sql, params or tuple())
  File "/tmp/Bazel.runfiles_b3f80ukr/runfiles/py_deps/pypi__sqlite_utils/sqlite_utils/db.py", line 422, in execute
    return self.conn.execute(sql, parameters)
sqlite3.OperationalError: malformed JSON


malformed JSON
Waiting up to 5 seconds.
Sent all pending logs.
```

**Comment by thinhha** [comment]
Hi Neil, thanks for your feedback. The error message could definitely be improved. Would you mind sharing the configs YAML used in this example? We'd need to check what the issue here so we can throw a better error message when it occurs.

**Comment by kolban-google** [comment]
Here is the YAML that I used:

```
entities:
  SALES_TABLE:
    source_database: BIGQUERY
    table_name: sales2
    dataset_name: clouddq
    project_name: kolban-dataplex
    columns:
      DATE_ID:
        name: date
        data_type: DATE
        description: date description
      WIDGET:
        name: widget
        data_type: STRING
        description: widget description
      QUANTITY:
        name: quantity
        data_type: INTEGER
        description: quantity description
      UNIT_PRICE:
        name: unit_price
        data_type: FLOAT
        description: unit_price description
      STATE:
        name: ship_state
        data_type: STRING
        description: ship_state description

rules:
  NOT_BLANK:
    rule_type: NOT_BLANK
    dimension: completeness
  POSITIVE:
    rule_type: CUSTOM_SQL_EXPR
    dimension: correctness
    params:
      custom_sql_expr: "$column >= 0"
  NOT_TOO_HIGH:
    rule_type: CUSTOM_SQL_EXPR
    dimension: correctness
    params:
      custom_sql_expr: "$column < 1000"

rule_dimensions:
  - consistency
  - correctness
  - duplication
  - completeness
  - conformance
  - integrity

row_filters:
  NONE:
    filter_sql_expr: "True"

rule_bindings:
  SALES_WIDGET:
    entity_id: SALES_TABLE
    column_id: WIDGET
    row_filter_id: NONE
    rule_ids:
      - NOT_BLANK
  SALES_QUANTITY:
    entity_id: SALES_TABLE
    column_id: QUANTITY
    row_filter_id: NONE
    rule_ids: POSITIVE
```

The working YAML was the last line which should have read:
```
    rule_ids:
      - POSITIVE
```

**Comment by thinhha** [comment]
Thank you Neil. Sorry for the delayed response. I believe I know what needs to be fixed and will work on it this week.
