### ISSUE TITLE
Cannot locate dbt_extractor

### ISSUE THREAD

**Issue by hugohjerten** [GoogleCloudPlatform/cloud-data-quality#223]
To have a setup that can be run on my mac, I'm setting up a debian-11-based Dockerfile containing the `clouddq_executable`. 
However, when executing the zipfile, I'm encountering the following error:
```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/clouddq/clouddq/main.py", line 39, in <module>
    from clouddq.runners.dbt.dbt_runner import DbtRunner
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/clouddq/clouddq/runners/dbt/dbt_runner.py", line 26, in <module>
    from clouddq.runners.dbt.dbt_utils import run_dbt
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/clouddq/clouddq/runners/dbt/dbt_utils.py", line 25, in <module>
    from dbt.main import main as dbt
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/main.py", line 18, in <module>
    import dbt.task.build as build_task
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/task/build.py", line 1, in <module>
    from .run import RunTask, ModelRunner as run_model_runner
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/task/compile.py", line 3, in <module>
    from .runnable import GraphRunnableTask
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/task/runnable.py", line 54, in <module>
    from dbt.parser.manifest import ManifestLoader
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/parser/__init__.py", line 8, in <module>
    from .models import ModelParser  # noqa
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_core/dbt/parser/models.py", line 17, in <module>
    from dbt_extractor import ExtractionError, py_extract_from_source  # type: ignore
  File "/tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_extractor/dbt_extractor/__init__.py", line 1, in <module>
    from .dbt_extractor import *
ImportError: /tmp/Bazel.runfiles_24wvewkh/runfiles/py_deps/pypi__dbt_extractor/dbt_extractor/dbt_extractor.abi3.so: cannot open shared object file: No such file or directory
```

My Dockerfile looks as follows:
```Dockerfile
ARG PYTHON_VERSION=3.9.7
ARG TARGET_PYTHON_INTERPRETER=3.9
FROM python:${PYTHON_VERSION}-slim-bullseye

ARG TARGET_OS=debian_11
ARG TARGET_PYTHON_INTERPRETER
ARG CLOUDDQ_RELEASE_VERSION=1.0.3

# Replace http with https
RUN sed -i 's/http/https/g' /etc/apt/sources.list
RUN apt-get update -y && apt-get upgrade -y && apt-get -y install wget

RUN wget -O \
    clouddq_executable.zip \
    https://github.com/GoogleCloudPlatform/cloud-data-quality/releases/download/v${CLOUDDQ_RELEASE_VERSION}/clouddq_executable_v${CLOUDDQ_RELEASE_VERSION}_${TARGET_OS}_python${TARGET_PYTHON_INTERPRETER}.zip

ENTRYPOINT [ "python3", "clouddq_executable.zip", "--help" ]
```

Any help or pointers on why the `dbt_extractor.abi3.so` module can't seem to be located, are greatly appreciated.

**Comment by jordiortegon** [comment]
Did anyone else ran into this problem? Could it be due to access to LD_LIBRARY_PATH?

**Comment by jordiortegon** [comment]
@thinhha would it make sense to be able to create a docker image template for local deployments so there's another option in the user manual tutorial?
